COMMENT ON TABLE common.dim_date IS 'Natural-key dimension: date. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_customer_segment IS 'Natural-key dimension: customer segment. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_market IS 'Natural-key dimension: market. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_order_date IS 'Natural-key dimension: order date. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_product_category IS 'Natural-key dimension: product category. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_region IS 'Natural-key dimension: region. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.dim_shipping_mode IS 'Natural-key dimension: shipping mode. Independent source-domain meanings apply.';
COMMENT ON TABLE dataco.fact_delivery_performance IS 'One DataCo order with consistent shipment attributes and eligible-outcome flag.';
COMMENT ON TABLE dataco.fact_orders IS 'One DataCo order line, uniquely keyed by order_item_id. Repeated order IDs are expected.';
COMMENT ON TABLE dataco.fact_profitability IS 'One DataCo order-line sales/profit record, not a duplicated order-level total.';
COMMENT ON TABLE m5.bridge_date_event IS 'One calendar date/event pair; both source events supported; avoid sales join fanout.';
COMMENT ON TABLE m5.dim_category IS 'Natural-key dimension: category. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.dim_department IS 'Natural-key dimension: department. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.dim_event IS 'Natural-key dimension: event. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.dim_product IS 'Natural-key dimension: product. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.dim_state IS 'Natural-key dimension: state. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.dim_store IS 'Natural-key dimension: store. Independent source-domain meanings apply.';
COMMENT ON TABLE m5.fact_forecast IS 'One row per M5 item-store-origin-target-date-selected-model.';
COMMENT ON TABLE m5.fact_forecast_accuracy IS 'One row per item-store-origin-date-candidate model; keep model/fold filters explicit.';
COMMENT ON TABLE m5.fact_inventory_policy IS 'One row per item-store-as-of-service scenario; simulated inventory only.';
COMMENT ON TABLE m5.fact_inventory_simulation IS 'One row per item-store-date-policy-scenario-run-service; simulated daily lost-sales replay.';
COMMENT ON TABLE m5.fact_sales_daily IS 'One row per M5 item-store-calendar day. Recorded units and listed-price revenue.';
COMMENT ON TABLE m5.fact_sell_price IS 'One row per M5 item-store-retail-week price.';
COMMENT ON COLUMN common.dim_date.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN common.dim_date.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN common.dim_date.year IS 'Calendar year.';
COMMENT ON COLUMN common.dim_date.month IS 'Calendar month 1–12.';
COMMENT ON COLUMN common.dim_date.quarter IS 'Calendar quarter 1–4.';
COMMENT ON COLUMN dataco.dim_customer_segment.customer_segment IS 'Normalized business customer segment; no personal identity.';
COMMENT ON COLUMN dataco.dim_market.market IS 'Normalized DataCo market; independent of M5 geography.';
COMMENT ON COLUMN dataco.dim_order_date.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN dataco.dim_order_date.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN dataco.dim_order_date.year IS 'Calendar year.';
COMMENT ON COLUMN dataco.dim_order_date.month IS 'Calendar month 1–12.';
COMMENT ON COLUMN dataco.dim_order_date.quarter IS 'Calendar quarter 1–4.';
COMMENT ON COLUMN dataco.dim_product_category.category IS 'Normalized DataCo product category; independent of M5 categories.';
COMMENT ON COLUMN dataco.dim_region.region IS 'Normalized DataCo order region.';
COMMENT ON COLUMN dataco.dim_shipping_mode.shipping_mode IS 'Normalized DataCo shipping service name.';
COMMENT ON COLUMN dataco.fact_delivery_performance.order_id IS 'DataCo business order key; repeated across order lines, not a customer identity.';
COMMENT ON COLUMN dataco.fact_delivery_performance.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN dataco.fact_delivery_performance.order_date IS 'Parsed DataCo order calendar date; time of day discarded.';
COMMENT ON COLUMN dataco.fact_delivery_performance.shipping_mode IS 'Normalized DataCo shipping service name.';
COMMENT ON COLUMN dataco.fact_delivery_performance.market IS 'Normalized DataCo market; independent of M5 geography.';
COMMENT ON COLUMN dataco.fact_delivery_performance.region IS 'Normalized DataCo order region.';
COMMENT ON COLUMN dataco.fact_delivery_performance.customer_segment IS 'Normalized business customer segment; no personal identity.';
COMMENT ON COLUMN dataco.fact_delivery_performance.actual_shipping_days IS 'Source reported actual shipping duration in days; not last-mile scan evidence.';
COMMENT ON COLUMN dataco.fact_delivery_performance.scheduled_shipping_days IS 'Source promised shipping duration in days.';
COMMENT ON COLUMN dataco.fact_delivery_performance.delivery_eligible IS 'True for valid 0–configured-max shipping durations excluding cancelled/suspected-fraud orders.';
COMMENT ON COLUMN dataco.fact_delivery_performance.late_order IS '1 when actual shipping exceeds scheduled, 0 when on time, null if ineligible.';
COMMENT ON COLUMN dataco.fact_delivery_performance.delay_days IS 'Signed actual minus scheduled shipping days on eligible orders.';
COMMENT ON COLUMN dataco.fact_delivery_performance.positive_delay_days IS 'Maximum of signed delay and zero; null if ineligible.';
COMMENT ON COLUMN dataco.fact_orders.order_item_id IS 'Unique DataCo business order-line key.';
COMMENT ON COLUMN dataco.fact_orders.order_id IS 'DataCo business order key; repeated across order lines, not a customer identity.';
COMMENT ON COLUMN dataco.fact_orders.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN dataco.fact_orders.order_date IS 'Parsed DataCo order calendar date; time of day discarded.';
COMMENT ON COLUMN dataco.fact_orders.category IS 'Normalized DataCo product category; independent of M5 categories.';
COMMENT ON COLUMN dataco.fact_orders.market IS 'Normalized DataCo market; independent of M5 geography.';
COMMENT ON COLUMN dataco.fact_orders.region IS 'Normalized DataCo order region.';
COMMENT ON COLUMN dataco.fact_orders.shipping_mode IS 'Normalized DataCo shipping service name.';
COMMENT ON COLUMN dataco.fact_orders.customer_segment IS 'Normalized business customer segment; no personal identity.';
COMMENT ON COLUMN dataco.fact_orders.product_name IS 'Normalized DataCo product label.';
COMMENT ON COLUMN dataco.fact_orders.quantity IS 'Source DataCo order-line quantity.';
COMMENT ON COLUMN dataco.fact_orders.sales IS 'Configured DataCo line net-sales amount; defaults to order_item_total.';
COMMENT ON COLUMN dataco.fact_orders.profit IS 'Configured DataCo line benefit amount; defaults to benefit_per_order; not repeated alias sum.';
COMMENT ON COLUMN dataco.fact_orders.invalid_sales_flag IS 'Negative configured sales or negative quantity; excluded from headline profit measures.';
COMMENT ON COLUMN dataco.fact_orders.abnormal_profit_flag IS 'Absolute line profit greater than twice absolute line sales; flag only, not automatic deletion.';
COMMENT ON COLUMN dataco.fact_profitability.order_item_id IS 'Unique DataCo business order-line key.';
COMMENT ON COLUMN dataco.fact_profitability.sales IS 'Configured DataCo line net-sales amount; defaults to order_item_total.';
COMMENT ON COLUMN dataco.fact_profitability.profit IS 'Configured DataCo line benefit amount; defaults to benefit_per_order; not repeated alias sum.';
COMMENT ON COLUMN dataco.fact_profitability.profit_margin IS 'Aggregate or line profit / matching sales, depending on table grain; undefined at zero sales.';
COMMENT ON COLUMN dataco.fact_profitability.loss_making_line IS 'True if a DataCo line has negative configured profit.';
COMMENT ON COLUMN m5.bridge_date_event.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN m5.bridge_date_event.event_name IS 'First source calendar event name; nullable.';
COMMENT ON COLUMN m5.dim_category.category_id IS 'M5 category natural key.';
COMMENT ON COLUMN m5.dim_department.department_id IS 'M5 department natural key.';
COMMENT ON COLUMN m5.dim_department.category_id IS 'M5 category natural key.';
COMMENT ON COLUMN m5.dim_event.event_name IS 'First source calendar event name; nullable.';
COMMENT ON COLUMN m5.dim_event.event_type IS 'First source calendar event type; nullable.';
COMMENT ON COLUMN m5.dim_product.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.dim_product.department_id IS 'M5 department natural key.';
COMMENT ON COLUMN m5.dim_product.category_id IS 'M5 category natural key.';
COMMENT ON COLUMN m5.dim_state.state_id IS 'M5 state code CA, TX or WI.';
COMMENT ON COLUMN m5.dim_store.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.dim_store.state_id IS 'M5 state code CA, TX or WI.';
COMMENT ON COLUMN m5.fact_forecast.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_forecast.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_forecast.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN m5.fact_forecast.origin IS 'Last historical date available to the forecast.';
COMMENT ON COLUMN m5.fact_forecast.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN m5.fact_forecast.horizon IS 'Integer number of days after origin.';
COMMENT ON COLUMN m5.fact_forecast.model IS 'Forecast or classifier name; different forecast levels must not be pooled.';
COMMENT ON COLUMN m5.fact_forecast.forecast_units IS 'Nonnegative model prediction in units for one item-store-date-origin-model.';
COMMENT ON COLUMN m5.fact_forecast.lower_80 IS 'Lower empirical residual bound for nominal 80% interval, clipped at zero and below point.';
COMMENT ON COLUMN m5.fact_forecast.upper_80 IS 'Upper empirical residual bound for nominal 80% interval, at least point forecast.';
COMMENT ON COLUMN m5.fact_forecast.lower_95 IS 'Lower empirical residual bound for nominal 95% interval; not additive into portfolio coverage.';
COMMENT ON COLUMN m5.fact_forecast.upper_95 IS 'Upper empirical residual bound for nominal 95% interval; not additive into portfolio coverage.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.origin IS 'Last historical date available to the forecast.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.model IS 'Forecast or classifier name; different forecast levels must not be pooled.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.fold IS 'Chronological rolling-origin fold index.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.split_role IS 'Calibration, selection or locked test role.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.actual_units IS 'Observed held-out M5 sales units matched to a forecast.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.forecast_units IS 'Nonnegative model prediction in units for one item-store-date-origin-model.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.error IS 'Forecast units minus actual units; positive means overprediction.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.absolute_error IS 'Absolute value of row prediction error.';
COMMENT ON COLUMN m5.fact_forecast_accuracy.scale IS 'Mean squared training first difference after first nonzero sale; undefined for constants.';
COMMENT ON COLUMN m5.fact_inventory_policy.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_inventory_policy.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_inventory_policy.as_of_date IS 'Snapshot date at which an inventory recommendation was generated.';
COMMENT ON COLUMN m5.fact_inventory_policy.target_service_level IS 'Scenario cycle-service target in (0,1); does not equal fill rate.';
COMMENT ON COLUMN m5.fact_inventory_policy.average_daily_demand IS 'Trailing 90-day pre-origin recorded-sales mean for an item-store.';
COMMENT ON COLUMN m5.fact_inventory_policy.forecast_daily_demand IS 'Mean predicted daily units over the planning horizon.';
COMMENT ON COLUMN m5.fact_inventory_policy.initial_inventory IS 'Assumed opening on-hand units before first simulation demand.';
COMMENT ON COLUMN m5.fact_inventory_policy.estimated_unit_cost IS 'Assumed cost-to-price ratio times last known price, with positive floor.';
COMMENT ON COLUMN m5.fact_inventory_policy.safety_stock IS 'Normal-approximation lead-time buffer units based on assumed service level.';
COMMENT ON COLUMN m5.fact_inventory_policy.reorder_point IS 'Expected lead-time demand plus lead-time safety stock; continuous-review reference.';
COMMENT ON COLUMN m5.fact_inventory_policy.eoq IS 'Square root of 2 × annualized units × fixed ordering cost / annual per-unit holding cost.';
COMMENT ON COLUMN m5.fact_inventory_policy.days_of_supply IS 'Assumed initial inventory / forecast daily mean; undefined for zero mean.';
COMMENT ON COLUMN m5.fact_inventory_policy.inventory_value IS 'Assumed initial stock multiplied by estimated unit cost.';
COMMENT ON COLUMN m5.fact_inventory_policy.stockout_probability IS 'Normal lead-time demand tail above initial stock assuming no initial incoming POs.';
COMMENT ON COLUMN m5.fact_inventory_policy.recommended_order_quantity IS 'Larger of EOQ or target shortage, rounded to MOQ/case pack, zero if no shortage.';
COMMENT ON COLUMN m5.fact_inventory_policy.excess_units IS 'Positive initial inventory above protection order-up-to target.';
COMMENT ON COLUMN m5.fact_inventory_policy.excess_value IS 'Excess units multiplied by estimated unit cost.';
COMMENT ON COLUMN m5.fact_inventory_simulation.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_inventory_simulation.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_inventory_simulation.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN m5.fact_inventory_simulation.policy IS 'baseline or optimized replenishment policy.';
COMMENT ON COLUMN m5.fact_inventory_simulation.scenario IS 'Base or named one-factor-at-a-time sensitivity case.';
COMMENT ON COLUMN m5.fact_inventory_simulation.run_id IS 'Monte Carlo repeat index; average repeated worlds rather than summing.';
COMMENT ON COLUMN m5.fact_inventory_simulation.target_service_level IS 'Scenario cycle-service target in (0,1); does not equal fill rate.';
COMMENT ON COLUMN m5.fact_inventory_simulation.opening_inventory IS 'On-hand units before today''s receipts and demand.';
COMMENT ON COLUMN m5.fact_inventory_simulation.arrivals IS 'Units received today from previously placed purchase orders.';
COMMENT ON COLUMN m5.fact_inventory_simulation.actual_demand IS 'Recorded held-out sales used as simulation demand proxy, not uncensored demand.';
COMMENT ON COLUMN m5.fact_inventory_simulation.forecast_demand IS 'Daily origin-time forecast passed into inventory replay.';
COMMENT ON COLUMN m5.fact_inventory_simulation.fulfilled_units IS 'Minimum of available inventory and observed demand proxy.';
COMMENT ON COLUMN m5.fact_inventory_simulation.lost_sales_units IS 'Demand proxy minus fulfilled units; no backorders carried.';
COMMENT ON COLUMN m5.fact_inventory_simulation.order_quantity IS 'Units ordered after today''s demand at a review opportunity.';
COMMENT ON COLUMN m5.fact_inventory_simulation.in_transit_units IS 'All placed units still awaiting arrival at end of day, including new orders.';
COMMENT ON COLUMN m5.fact_inventory_simulation.closing_inventory IS 'Opening units plus receipts minus fulfillment; nonnegative.';
COMMENT ON COLUMN m5.fact_inventory_simulation.stockout_event IS '1 when any demand is lost on the item-store-day.';
COMMENT ON COLUMN m5.fact_inventory_simulation.holding_cost IS 'Closing units × unit cost × annual holding rate / 365.';
COMMENT ON COLUMN m5.fact_inventory_simulation.ordering_cost IS 'Fixed assumed order cost if a positive order was placed, otherwise zero.';
COMMENT ON COLUMN m5.fact_inventory_simulation.lost_sale_cost IS 'Lost units multiplied by assumed lost-sale penalty.';
COMMENT ON COLUMN m5.fact_inventory_simulation.total_inventory_cost IS 'Holding + ordering + lost-sale cost; excludes purchase spend and terminal valuation.';
COMMENT ON COLUMN m5.fact_inventory_simulation.lost_sales_value IS 'Lost units valued at origin-time selling price; hypothetical revenue loss.';
COMMENT ON COLUMN m5.fact_inventory_simulation.estimated_unit_cost IS 'Assumed cost-to-price ratio times last known price, with positive floor.';
COMMENT ON COLUMN m5.fact_inventory_simulation.completed_cycles IS 'Completed receipt-to-receipt replenishment cycles; first and unfinished cycles excluded.';
COMMENT ON COLUMN m5.fact_inventory_simulation.successful_cycles IS 'Completed cycles with no lost demand between consecutive receipts.';
COMMENT ON COLUMN m5.fact_sales_daily.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_sales_daily.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_sales_daily.date_key IS 'Integer YYYYMMDD key derived from calendar date.';
COMMENT ON COLUMN m5.fact_sales_daily.date IS 'Calendar date represented by the observation or prediction.';
COMMENT ON COLUMN m5.fact_sales_daily.units_sold IS 'M5 recorded sales units; availability-censored demand is possible.';
COMMENT ON COLUMN m5.fact_sales_daily.sell_price IS 'M5 listed weekly item-store selling price, source currency per unit.';
COMMENT ON COLUMN m5.fact_sales_daily.revenue IS 'M5 recorded units times weekly price; zero-unit rows have zero revenue even with no price.';
COMMENT ON COLUMN m5.fact_sales_daily.wm_yr_wk IS 'M5 retail calendar week identifier.';
COMMENT ON COLUMN m5.fact_sales_daily.snap_flag IS 'Source state-specific SNAP eligibility indicator, 0 or 1; not a promotion flag.';
COMMENT ON COLUMN m5.fact_sales_daily.event_flag IS '1 if either source event is present on the date.';
COMMENT ON COLUMN m5.fact_sell_price.item_id IS 'M5 item natural key; not a DataCo product identifier.';
COMMENT ON COLUMN m5.fact_sell_price.store_id IS 'M5 store natural key.';
COMMENT ON COLUMN m5.fact_sell_price.wm_yr_wk IS 'M5 retail calendar week identifier.';
COMMENT ON COLUMN m5.fact_sell_price.sell_price IS 'M5 listed weekly item-store selling price, source currency per unit.';
